/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.ifnmg.psc.Apresentacao;

import br.edu.ifnmg.psc.Aplicacao.Cliente;
import br.edu.ifnmg.psc.Aplicacao.Compra;
import br.edu.ifnmg.psc.Aplicacao.CompraRepositorio;
import br.edu.ifnmg.psc.Aplicacao.Fornecedor;
import br.edu.ifnmg.psc.Aplicacao.FornecedorRepositorio;
import br.edu.ifnmg.psc.Aplicacao.ItensCompra;
import br.edu.ifnmg.psc.Aplicacao.Produto;
import br.edu.ifnmg.psc.Aplicacao.ProdutoRepositorio;
import br.edu.ifnmg.psc.Persistencia.FornecedorDAO;
import br.edu.ifnmg.psc.Persistencia.ProdutoDAO;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author thais
 */
public class TelaEfetuarCompras extends javax.swing.JInternalFrame {

    CompraRepositorio dao = GerenciadorReferencias.getCompra();
    FornecedorRepositorio daoFornecedor = GerenciadorReferencias.getFornecedor();
    ProdutoRepositorio daoProduto = GerenciadorReferencias.getProduto();
    ArrayList<ItensCompra> listaCompras = new ArrayList<>();
    String nomeProduto;
    Calendar calendario = GregorianCalendar.getInstance();
    
    DateFormat df = new SimpleDateFormat("dd/MM/yyyy");
    Compra entidade;
    GerenciarCompras listagem;
    /**
     * Creates new form TelaGerenciamentoCompras
     */
    public TelaEfetuarCompras() {
        initComponents();
        carregarCombo();
        preencheTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelCarrGerenComp = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblItensCompras = new javax.swing.JTable();
        PanelDadosCompra = new javax.swing.JPanel();
        LblForncedor = new javax.swing.JLabel();
        cmbFornecedor = new javax.swing.JComboBox();
        LblData = new javax.swing.JLabel();
        txtData = new javax.swing.JFormattedTextField();
        PanelCompras = new javax.swing.JPanel();
        LblProdutos = new javax.swing.JLabel();
        LblQuantidade = new javax.swing.JLabel();
        cmbProduto = new javax.swing.JComboBox();
        spinnerQuantidade = new javax.swing.JSpinner();
        BtnAdicionar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        BtnEncaminhar = new javax.swing.JButton();
        BtnVoltar = new javax.swing.JButton();
        BtnCancelar = new javax.swing.JButton();

        setTitle("Efetuar Compras");

        PanelCarrGerenComp.setBorder(javax.swing.BorderFactory.createTitledBorder("Carrinho de compras"));

        tblItensCompras.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblItensCompras.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_LAST_COLUMN);
        tblItensCompras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblItensComprasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblItensCompras);

        javax.swing.GroupLayout PanelCarrGerenCompLayout = new javax.swing.GroupLayout(PanelCarrGerenComp);
        PanelCarrGerenComp.setLayout(PanelCarrGerenCompLayout);
        PanelCarrGerenCompLayout.setHorizontalGroup(
            PanelCarrGerenCompLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(PanelCarrGerenCompLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelCarrGerenCompLayout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 465, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(223, 223, 223)))
        );
        PanelCarrGerenCompLayout.setVerticalGroup(
            PanelCarrGerenCompLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 383, Short.MAX_VALUE)
            .addGroup(PanelCarrGerenCompLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelCarrGerenCompLayout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        PanelDadosCompra.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados da compra"));

        LblForncedor.setText("Fornecedor:");

        cmbFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbFornecedorActionPerformed(evt);
            }
        });

        LblData.setText("Data:");

        try {
            txtData.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout PanelDadosCompraLayout = new javax.swing.GroupLayout(PanelDadosCompra);
        PanelDadosCompra.setLayout(PanelDadosCompraLayout);
        PanelDadosCompraLayout.setHorizontalGroup(
            PanelDadosCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDadosCompraLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelDadosCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LblData, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LblForncedor, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(PanelDadosCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cmbFornecedor, 0, 215, Short.MAX_VALUE)
                    .addComponent(txtData))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelDadosCompraLayout.setVerticalGroup(
            PanelDadosCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelDadosCompraLayout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addGroup(PanelDadosCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblData, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelDadosCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblForncedor, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52))
        );

        PanelCompras.setBorder(javax.swing.BorderFactory.createTitledBorder("Efetuar Compras"));

        LblProdutos.setText("Produto:");

        LblQuantidade.setText("Quantidade:");

        spinnerQuantidade.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        BtnAdicionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/add.png"))); // NOI18N
        BtnAdicionar.setText("Adicionar");
        BtnAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAdicionarActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/removeItem.png"))); // NOI18N
        jButton1.setText("Remover");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelComprasLayout = new javax.swing.GroupLayout(PanelCompras);
        PanelCompras.setLayout(PanelComprasLayout);
        PanelComprasLayout.setHorizontalGroup(
            PanelComprasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelComprasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelComprasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PanelComprasLayout.createSequentialGroup()
                        .addComponent(LblQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(spinnerQuantidade))
                    .addComponent(LblProdutos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PanelComprasLayout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(cmbProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelComprasLayout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(36, 36, 36)
                        .addComponent(BtnAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(58, 58, 58))
        );
        PanelComprasLayout.setVerticalGroup(
            PanelComprasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelComprasLayout.createSequentialGroup()
                .addGroup(PanelComprasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelComprasLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(cmbProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PanelComprasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LblQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(spinnerQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(PanelComprasLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(LblProdutos, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(PanelComprasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(BtnAdicionar))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        BtnEncaminhar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/1489414743_Document_file_contract_send.png"))); // NOI18N
        BtnEncaminhar.setText("Encaminhar");
        BtnEncaminhar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEncaminharActionPerformed(evt);
            }
        });

        BtnVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/voltar_32.png"))); // NOI18N
        BtnVoltar.setText("Voltar");
        BtnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnVoltarActionPerformed(evt);
            }
        });

        BtnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cancela.png"))); // NOI18N
        BtnCancelar.setText("Cancelar");
        BtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BtnVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BtnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BtnEncaminhar, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(PanelDadosCompra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(PanelCompras, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(PanelCarrGerenComp, javax.swing.GroupLayout.PREFERRED_SIZE, 499, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(PanelCompras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(PanelDadosCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(PanelCarrGerenComp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(BtnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(BtnEncaminhar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(BtnVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbFornecedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbFornecedorActionPerformed

    private void BtnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnVoltarActionPerformed
        this.doDefaultCloseAction();
        TelaPrincipal.MenuPrincipal.setVisible(true);
    }//GEN-LAST:event_BtnVoltarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       if(JOptionPane.showConfirmDialog(rootPane, "Deseja realmente remover o item?") == 0){
            
            for(ItensCompra itens: listaCompras){
                if(itens.getProduto().getNome().equals(nomeProduto)){
                    listaCompras.remove(itens);
                    preencheTabela();
                    JOptionPane.showMessageDialog(rootPane, "Item removido com sucesso!");
                }
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tblItensComprasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblItensComprasMouseClicked
        int linha = tblItensCompras.getSelectedRow();
        nomeProduto = (String) tblItensCompras.getModel().getValueAt(linha, 0);  //(VendaItem) tblItens.getModel().getValueAt(linha, 3);

    }//GEN-LAST:event_tblItensComprasMouseClicked

    private void BtnAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAdicionarActionPerformed
       Produto produtoSelecionado = null;
        ArrayList<Produto> listaProdutos = daoProduto.listarProdutos();
        for(Produto novo: listaProdutos){
            if(novo.getNome().equals(cmbProduto.getSelectedItem()))
                produtoSelecionado = novo;
        }
        
        int quantidade = (Integer)spinnerQuantidade.getValue();
        ItensCompra item = new ItensCompra(quantidade, produtoSelecionado);
        
        if(produtoSelecionado==null || produtoSelecionado.equals("Selecione") || quantidade==0){
            JOptionPane.showMessageDialog(rootPane, "Erro ao adicionar item", "Mensagem de erro", JOptionPane.ERROR_MESSAGE);
        }
        
       /* if(listaCompras.contains(cmbProduto.getSelectedItem())){
                quantidade+=(Integer) spinQuantidade.getValue();
                System.out.println("Quantidade atual: "+quantidade);
                int index = listaCompras.indexOf(cmbProduto.getSelectedItem());
        }*/
        if(!listaCompras.contains(item)){
            listaCompras.add(item);
        }
        preencheTabela();
    }//GEN-LAST:event_BtnAdicionarActionPerformed

    private void BtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCancelarActionPerformed
        if(JOptionPane.showConfirmDialog(rootPane, "Deseja realmente cancelar a Operação?") == 0){
            this.doDefaultCloseAction();
        }
    }//GEN-LAST:event_BtnCancelarActionPerformed

    private void BtnEncaminharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEncaminharActionPerformed
        if(verificaCampos()){
            try {
                extraiCampos();
                if(JOptionPane.showConfirmDialog(rootPane, "Deseja realmente Efetuar a Compra?") == 0){
                    preencheObjeto();
                    
                    if(dao.Salvar(entidade)){
                        JOptionPane.showMessageDialog(rootPane, "Compra Concluída com Sucesso!");
                        preencheCampos();
                        limpaCampos();
                    }
                    else JOptionPane.showMessageDialog(rootPane, "Erro durante a execução");
                } else JOptionPane.showMessageDialog(rootPane, "Operação cancelada!");
            } catch (ParseException ex) {
                ex.printStackTrace();
            }
        }
        else JOptionPane.showMessageDialog(rootPane, "Dados Inválidos","Mensagem de Erro",JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_BtnEncaminharActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAdicionar;
    private javax.swing.JButton BtnCancelar;
    private javax.swing.JButton BtnEncaminhar;
    private javax.swing.JButton BtnVoltar;
    private javax.swing.JLabel LblData;
    private javax.swing.JLabel LblForncedor;
    private javax.swing.JLabel LblProdutos;
    private javax.swing.JLabel LblQuantidade;
    private javax.swing.JPanel PanelCarrGerenComp;
    private javax.swing.JPanel PanelCompras;
    private javax.swing.JPanel PanelDadosCompra;
    private javax.swing.JComboBox cmbFornecedor;
    private javax.swing.JComboBox cmbProduto;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner spinnerQuantidade;
    private javax.swing.JTable tblItensCompras;
    private javax.swing.JFormattedTextField txtData;
    // End of variables declaration//GEN-END:variables

    private void carregarCombo() {
       daoFornecedor = new FornecedorDAO();
       ArrayList<Fornecedor> listaFornecedor = daoFornecedor.listarFornecedor();
       cmbFornecedor.addItem("Selecione");
       for(Fornecedor novo: listaFornecedor){
           cmbFornecedor.addItem(novo.getNome());
       }
       
       daoProduto = new ProdutoDAO();
       ArrayList<Produto> listaProdutos = daoProduto.listarProdutos();
       cmbProduto.addItem("Selecione");
       for(Produto novo: listaProdutos){
           cmbProduto.addItem(novo.getNome());
       }
       
    }
    
    private void preencheCampos() {
        txtData.setText(df.format(entidade.getData())); 
        cmbFornecedor.setSelectedItem(entidade.getFornecedor().getNome());
        listaCompras.addAll(entidade.getItens());
        preencheTabela();
    }

    private void preencheTabela() {
        DefaultTableModel itens = new DefaultTableModel();
        
        itens.addColumn("Produto");
        itens.addColumn("Quantidade");
        
        for(ItensCompra i : listaCompras){
            Vector valor = new Vector();
            valor.add(i.getProduto().getNome());
            valor.add(i.getQuantidade());
            valor.add(i);
            itens.addRow(valor);
        }
        tblItensCompras.setModel(itens);
    }

    private boolean verificaCampos() {
        if(txtData.getText().equals(""))
            return false;
        if(cmbFornecedor.getSelectedItem().equals("Selecione"))
            return false;
        if(listaCompras.size()==0)
            return false;
        return true;
    }

    private void extraiCampos() throws ParseException {
        entidade = new Compra();
        if(!txtData.getText().equals("")){
            SimpleDateFormat format = new SimpleDateFormat("dd/MM/yyyy");
            java.sql.Date data = new java.sql.Date(format.parse(txtData.getText()).getTime());
            entidade.setData(data);
        }
        
        ArrayList<Fornecedor> listaFornecedores = daoFornecedor.listarFornecedor();
        for(Fornecedor fornecedor: listaFornecedores){
            if(cmbProduto.getSelectedItem().equals(fornecedor.getNome()))
                entidade.setFornecedor(fornecedor);
        }
        
        entidade.setItens(listaCompras);
    }

    private void preencheObjeto() {
        try {
            
            ArrayList<Fornecedor> listaFornecedores = daoFornecedor.listarFornecedor();
            for(Fornecedor novo: listaFornecedores){
                if(novo.getNome().equals(cmbFornecedor.getSelectedItem()))
                    entidade.setFornecedor(novo);
            }
            
            SimpleDateFormat format = new SimpleDateFormat("dd/MM/yyyy");
            java.sql.Date data = new java.sql.Date(format.parse(txtData.getText()).getTime());
            entidade.setData(data);
        } catch (ParseException ex) {
            ex.printStackTrace();
        }
    }

    private void limpaCampos() {
        txtData.setText("");
        cmbFornecedor.setSelectedItem("Selecione");
        cmbProduto.setSelectedItem("Selecione");
        spinnerQuantidade.setValue(0);
        this.listaCompras.removeAll(listaCompras);
        preencheTabela();
        
    }

    void setEntidade(Compra entidade) {
      //  this.entidade = entidade;
      //  preencheCampos();
    }

    void setListagem(GerenciarCompras listagem) {
       // this.listagem = listagem;
    }
}
