/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.ifnmg.psc.Apresentacao;

import br.edu.ifnmg.psc.Aplicacao.ClienteRepositorio;
import br.edu.ifnmg.psc.Aplicacao.CompraRepositorio;
import br.edu.ifnmg.psc.Aplicacao.FuncionarioRepositorio;
import br.edu.ifnmg.psc.Aplicacao.ProdutoRepositorio;
import br.edu.ifnmg.psc.Aplicacao.VeiculoRepositorio;
import br.edu.ifnmg.psc.Aplicacao.VendaRepositorio;
import java.awt.BorderLayout;
import java.beans.PropertyVetoException;
import java.net.URL;
import java.text.ParseException;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.management.JMRuntimeException;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JRDataSource;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.data.JRBeanCollectionDataSource;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author victor
 */
public class TelaPrincipal extends javax.swing.JFrame{

    /**
     * Creates new form PrincipalDesktop
     */
    public TelaPrincipal() {
        initComponents();
        this.setExtendedState(this.MAXIMIZED_BOTH); 
        setContentPane(DesktopPrincipal);
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem2 = new javax.swing.JMenuItem();
        DesktopPrincipal = new javax.swing.JDesktopPane();
        MenuPrincipal = new javax.swing.JMenuBar();
        menuGerenciar = new javax.swing.JMenu();
        menuItemClientes = new javax.swing.JMenuItem();
        MenuItemCompras = new javax.swing.JMenuItem();
        itemFornecedores = new javax.swing.JMenuItem();
        menuItemFuncionarios = new javax.swing.JMenuItem();
        menuItemProdutos = new javax.swing.JMenuItem();
        MenuItemVeiculo = new javax.swing.JMenuItem();
        menuItemVendas = new javax.swing.JMenuItem();
        menuRelatorios = new javax.swing.JMenu();
        itemClientes = new javax.swing.JMenuItem();
        itemFuncionarios = new javax.swing.JMenuItem();
        itemProdutos = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        itemVendas = new javax.swing.JMenuItem();
        MenuSair = new javax.swing.JMenu();

        jMenuItem2.setText("jMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tela Principal");

        MenuPrincipal.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        MenuPrincipal.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N

        menuGerenciar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/gerenciar.png"))); // NOI18N
        menuGerenciar.setText("Gerenciar");

        menuItemClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/users.png"))); // NOI18N
        menuItemClientes.setText("Clientes");
        menuItemClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemClientesActionPerformed(evt);
            }
        });
        menuGerenciar.add(menuItemClientes);

        MenuItemCompras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/compra.png"))); // NOI18N
        MenuItemCompras.setText("Compras");
        MenuItemCompras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemComprasActionPerformed(evt);
            }
        });
        menuGerenciar.add(MenuItemCompras);

        itemFornecedores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fornecedores.png"))); // NOI18N
        itemFornecedores.setText("Fornecedores");
        itemFornecedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemFornecedoresActionPerformed(evt);
            }
        });
        menuGerenciar.add(itemFornecedores);

        menuItemFuncionarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/funcionarios.png"))); // NOI18N
        menuItemFuncionarios.setText("Funcionários");
        menuItemFuncionarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemFuncionariosActionPerformed(evt);
            }
        });
        menuGerenciar.add(menuItemFuncionarios);

        menuItemProdutos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/produto.png"))); // NOI18N
        menuItemProdutos.setText("Produtos");
        menuItemProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemProdutosActionPerformed(evt);
            }
        });
        menuGerenciar.add(menuItemProdutos);

        MenuItemVeiculo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/carro.png"))); // NOI18N
        MenuItemVeiculo.setText("Veículos");
        MenuItemVeiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemVeiculoActionPerformed(evt);
            }
        });
        menuGerenciar.add(MenuItemVeiculo);

        menuItemVendas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/venda.png"))); // NOI18N
        menuItemVendas.setText("Vendas");
        menuItemVendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemVendasActionPerformed(evt);
            }
        });
        menuGerenciar.add(menuItemVendas);

        MenuPrincipal.add(menuGerenciar);

        menuRelatorios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/relatorio.png"))); // NOI18N
        menuRelatorios.setText("Relatórios");

        itemClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/users.png"))); // NOI18N
        itemClientes.setText("Clientes");
        itemClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemClientesActionPerformed(evt);
            }
        });
        menuRelatorios.add(itemClientes);

        itemFuncionarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/funcionarios.png"))); // NOI18N
        itemFuncionarios.setText("Funcionários");
        itemFuncionarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemFuncionariosActionPerformed(evt);
            }
        });
        menuRelatorios.add(itemFuncionarios);

        itemProdutos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/produto.png"))); // NOI18N
        itemProdutos.setText("Produtos");
        itemProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemProdutosActionPerformed(evt);
            }
        });
        menuRelatorios.add(itemProdutos);

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/carro.png"))); // NOI18N
        jMenuItem1.setText("Veículos");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        menuRelatorios.add(jMenuItem1);

        itemVendas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/venda.png"))); // NOI18N
        itemVendas.setText("Vendas");
        itemVendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemVendasActionPerformed(evt);
            }
        });
        menuRelatorios.add(itemVendas);

        MenuPrincipal.add(menuRelatorios);

        MenuSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/sair.png"))); // NOI18N
        MenuSair.setText("Sair");
        MenuSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                MenuSairMousePressed(evt);
            }
        });
        MenuPrincipal.add(MenuSair);

        setJMenuBar(MenuPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DesktopPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 1041, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DesktopPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 457, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1051, 532));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void menuItemFuncionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemFuncionariosActionPerformed
       abreInternalFrame(new TelaGerenciarFuncionarios());
    }//GEN-LAST:event_menuItemFuncionariosActionPerformed

    private void menuItemClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemClientesActionPerformed
        try {
            abreInternalFrame(new TelaGerenciarClientes());
        } catch (ParseException ex) {
           ex.printStackTrace();
        }
    }//GEN-LAST:event_menuItemClientesActionPerformed

    private void menuItemVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemVendasActionPerformed
        try {
            abreInternalFrame(new TelaGerenciamentoVendas());
        } catch (ParseException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_menuItemVendasActionPerformed

    private void menuItemProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemProdutosActionPerformed
        try {
            abreInternalFrame(new TelaGerenciarProduto());
        } catch (ParseException ex) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_menuItemProdutosActionPerformed

    private void MenuItemComprasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemComprasActionPerformed
        abreInternalFrame(new TelaEfetuarCompras());
    }//GEN-LAST:event_MenuItemComprasActionPerformed

    private void MenuItemVeiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemVeiculoActionPerformed
        try {
            abreInternalFrame(new TelaGerenciarVeiculos());
        } catch (ParseException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_MenuItemVeiculoActionPerformed

    private void itemFornecedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemFornecedoresActionPerformed
        abreInternalFrame(new TelaGerenciarFornecedores());
    }//GEN-LAST:event_itemFornecedoresActionPerformed

    private void itemClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemClientesActionPerformed
        ClienteRepositorio dao = GerenciadorReferencias.getCliente();
        
        try {
            exibeRelatorioJasper("Clientes.jasper", dao.Buscar(null) );
        } catch (JRException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_itemClientesActionPerformed

    private void itemVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemVendasActionPerformed
        VendaRepositorio dao = GerenciadorReferencias.getVenda();
        
        try {
            exibeRelatorioJasper("Vendas.jasper", dao.Buscar(null) );
        } catch (JRException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_itemVendasActionPerformed

    private void itemProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemProdutosActionPerformed
        ProdutoRepositorio dao = GerenciadorReferencias.getProduto();

        try {
            exibeRelatorioJasper("Produtos.jasper", dao.Buscar(null));
        } catch (JRException ex) {
           ex.printStackTrace();
        }
    }//GEN-LAST:event_itemProdutosActionPerformed

    private void MenuSairMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuSairMousePressed
        if (JOptionPane.showConfirmDialog(null, "Deseja sair do sistema?")==0){
           this.dispose();
           new TelaLogin().setVisible(true);
           
        }
    }//GEN-LAST:event_MenuSairMousePressed

    private void itemFuncionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemFuncionariosActionPerformed
        FuncionarioRepositorio dao = GerenciadorReferencias.getFuncionario();

        try {
            exibeRelatorioJasper("Funcionarios.jasper", dao.Buscar(null));
        } catch (JRException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_itemFuncionariosActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        try {
            VeiculoRepositorio dao = GerenciadorReferencias.getVeiculo();
            exibeRelatorioJasper("Veiculos.jasper", dao.Buscar(null));
        } catch (JRException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }
     private void exibeRelatorioJasper(String caminho_relatorio, List dados) throws JRException {

        try {
            // Parâmetros
            Map parametros = new HashMap();

            // Pega o caminho do arquivo do relatório
            URL arquivo = getClass().getResource(caminho_relatorio);
            
            // Carrega o relatório na memória
            JasperReport relatorio = (JasperReport) JRLoader.loadObject(arquivo);
            
            JRDataSource fontededados = new JRBeanCollectionDataSource(dados, true);
            
            JasperPrint jasperPrint = JasperFillManager.fillReport(relatorio, parametros, fontededados);
            
            // Visualiza o relatório
            JasperViewer jrviewer = new JasperViewer(jasperPrint, false);
            
            jrviewer.setVisible(true);
        
        } catch (JMRuntimeException ex) {
            ex.printStackTrace();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JDesktopPane DesktopPrincipal;
    private javax.swing.JMenuItem MenuItemCompras;
    private javax.swing.JMenuItem MenuItemVeiculo;
    public static javax.swing.JMenuBar MenuPrincipal;
    private javax.swing.JMenu MenuSair;
    private javax.swing.JMenuItem itemClientes;
    private javax.swing.JMenuItem itemFornecedores;
    private javax.swing.JMenuItem itemFuncionarios;
    private javax.swing.JMenuItem itemProdutos;
    private javax.swing.JMenuItem itemVendas;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenu menuGerenciar;
    private javax.swing.JMenuItem menuItemClientes;
    private javax.swing.JMenuItem menuItemFuncionarios;
    private javax.swing.JMenuItem menuItemProdutos;
    private javax.swing.JMenuItem menuItemVendas;
    private javax.swing.JMenu menuRelatorios;
    // End of variables declaration//GEN-END:variables
    
    public void abreInternalFrame(JInternalFrame frame) {
        frame.setVisible(true);
        DesktopPrincipal.add(frame, BorderLayout.CENTER);
        try {
            frame.setSelected(true);
            frame.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
        DesktopPrincipal.setVisible(true);
        MenuPrincipal.setVisible(false);
        frame.setSize(DesktopPrincipal.getSize());
    }
}
