/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.ifnmg.psc.Apresentacao;

import br.edu.ifnmg.psc.Aplicacao.Cliente;
import br.edu.ifnmg.psc.Aplicacao.ClienteRepositorio;
import br.edu.ifnmg.psc.Aplicacao.ItensVenda;
import br.edu.ifnmg.psc.Aplicacao.Produto;
import br.edu.ifnmg.psc.Aplicacao.ProdutoRepositorio;
import br.edu.ifnmg.psc.Aplicacao.Venda;
import br.edu.ifnmg.psc.Aplicacao.VendaRepositorio;
import br.edu.ifnmg.psc.Persistencia.ClienteDAO;
import br.edu.ifnmg.psc.Persistencia.ProdutoDAO;
import java.math.BigDecimal;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author thais
 */
public class TelaEfetuarVenda extends javax.swing.JInternalFrame {

    VendaRepositorio dao = GerenciadorReferencias.getVenda();
    ClienteRepositorio daoCliente = GerenciadorReferencias.getCliente();
    ProdutoRepositorio daoProduto = GerenciadorReferencias.getProduto();
    
    Calendar calendario = GregorianCalendar.getInstance();
    
    DateFormat df = new SimpleDateFormat("dd/MM/yyyy");
    
    TelaGerenciamentoVendas listagem;
    
    Venda entidade;
    ItensVenda itemSelecionado;
    ArrayList<ItensVenda> listaCompras = new ArrayList<>();
    BigDecimal valorTotal = new BigDecimal("0.0");
    String produtoSelecionado;
    String nomeProduto;
    
    /**
     * Creates new form TelaEfetuarVenda
     */
    public TelaEfetuarVenda() {
        initComponents();
        carregarCombo();
    }

    public Venda getEntidade(){
        return entidade;
    }
    
    public void setEntidade(){
        this.entidade = entidade;
        preencheCampos();
    }
    
    public TelaGerenciamentoVendas getListagem(){
        return listagem;
    }
    
    public void setListagem(TelaGerenciamentoVendas listagem){
        this.listagem = listagem;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelEfeVend = new javax.swing.JPanel();
        LblProduto = new javax.swing.JLabel();
        LblQuantidade = new javax.swing.JLabel();
        cmbProduto = new javax.swing.JComboBox();
        spinQuantidade = new javax.swing.JSpinner();
        btnAdicionarItens = new javax.swing.JButton();
        btnRemover = new javax.swing.JButton();
        jPanelDadosVend = new javax.swing.JPanel();
        LblFormaPagamento = new javax.swing.JLabel();
        cmbFormaPagamento = new javax.swing.JComboBox();
        LblData = new javax.swing.JLabel();
        txtdata = new javax.swing.JFormattedTextField();
        LblCliente = new javax.swing.JLabel();
        cmbCliente = new javax.swing.JComboBox();
        jPanelCarrEfVend = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblItensVenda = new javax.swing.JTable();
        LblDesconto = new javax.swing.JLabel();
        txtDesconto = new javax.swing.JTextField();
        LblValorTotal = new javax.swing.JLabel();
        txtValorTotal = new javax.swing.JTextField();
        BtnVoltar = new javax.swing.JButton();
        BtnCancelar = new javax.swing.JButton();
        BtnFinal = new javax.swing.JButton();
        btnDesconto = new javax.swing.JButton();

        setTitle("Efetuar Venda");

        jPanelEfeVend.setBorder(javax.swing.BorderFactory.createTitledBorder("Efetuar Venda"));

        LblProduto.setText("Produto:");

        LblQuantidade.setText("Quantidade:");

        btnAdicionarItens.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/add.png"))); // NOI18N
        btnAdicionarItens.setText("Adicionar");
        btnAdicionarItens.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarItensActionPerformed(evt);
            }
        });

        btnRemover.setText("Remover");
        btnRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelEfeVendLayout = new javax.swing.GroupLayout(jPanelEfeVend);
        jPanelEfeVend.setLayout(jPanelEfeVendLayout);
        jPanelEfeVendLayout.setHorizontalGroup(
            jPanelEfeVendLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEfeVendLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelEfeVendLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(LblProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelEfeVendLayout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(cmbProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelEfeVendLayout.createSequentialGroup()
                        .addComponent(LblQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelEfeVendLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelEfeVendLayout.createSequentialGroup()
                                .addComponent(btnRemover, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(64, 64, 64)
                                .addComponent(btnAdicionarItens, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(spinQuantidade))))
                .addContainerGap())
        );
        jPanelEfeVendLayout.setVerticalGroup(
            jPanelEfeVendLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEfeVendLayout.createSequentialGroup()
                .addGroup(jPanelEfeVendLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelEfeVendLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(cmbProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelEfeVendLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LblQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(spinQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelEfeVendLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(LblProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanelEfeVendLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnAdicionarItens, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnRemover, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelDadosVend.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados da venda"));

        LblFormaPagamento.setText("Forma de pagamento:");

        cmbFormaPagamento.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione", "Dinheiro", "Débito", "Crédito" }));
        cmbFormaPagamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbFormaPagamentoActionPerformed(evt);
            }
        });

        LblData.setText("Data:");

        try {
            txtdata.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        LblCliente.setText("Cliente:");

        javax.swing.GroupLayout jPanelDadosVendLayout = new javax.swing.GroupLayout(jPanelDadosVend);
        jPanelDadosVend.setLayout(jPanelDadosVendLayout);
        jPanelDadosVendLayout.setHorizontalGroup(
            jPanelDadosVendLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDadosVendLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDadosVendLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelDadosVendLayout.createSequentialGroup()
                        .addComponent(LblCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanelDadosVendLayout.createSequentialGroup()
                        .addGroup(jPanelDadosVendLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelDadosVendLayout.createSequentialGroup()
                                .addComponent(LblData, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(121, 121, 121))
                            .addComponent(LblFormaPagamento, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanelDadosVendLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cmbFormaPagamento, 0, 203, Short.MAX_VALUE)
                            .addComponent(cmbCliente, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtdata))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelDadosVendLayout.setVerticalGroup(
            jPanelDadosVendLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDadosVendLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDadosVendLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblData, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtdata, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelDadosVendLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblFormaPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbFormaPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelDadosVendLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jPanelCarrEfVend.setBorder(javax.swing.BorderFactory.createTitledBorder("Carrinho de compras"));

        tblItensVenda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblItensVenda.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_LAST_COLUMN);
        tblItensVenda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblItensVendaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblItensVenda);

        javax.swing.GroupLayout jPanelCarrEfVendLayout = new javax.swing.GroupLayout(jPanelCarrEfVend);
        jPanelCarrEfVend.setLayout(jPanelCarrEfVendLayout);
        jPanelCarrEfVendLayout.setHorizontalGroup(
            jPanelCarrEfVendLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanelCarrEfVendLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCarrEfVendLayout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 676, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );
        jPanelCarrEfVendLayout.setVerticalGroup(
            jPanelCarrEfVendLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanelCarrEfVendLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCarrEfVendLayout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        LblDesconto.setText("Desconto(%):");

        LblValorTotal.setText("Valor Total:");

        BtnVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/voltar_32.png"))); // NOI18N
        BtnVoltar.setText("Voltar");
        BtnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnVoltarActionPerformed(evt);
            }
        });

        BtnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cancela.png"))); // NOI18N
        BtnCancelar.setText("Cancelar");
        BtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCancelarActionPerformed(evt);
            }
        });

        BtnFinal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/save.png"))); // NOI18N
        BtnFinal.setText("Salvar");
        BtnFinal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnFinalActionPerformed(evt);
            }
        });

        btnDesconto.setText("Descontar");
        btnDesconto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDescontoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jPanelDadosVend, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanelEfeVend, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(BtnVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LblDesconto, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(txtDesconto, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnDesconto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 224, Short.MAX_VALUE)
                        .addComponent(LblValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(BtnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BtnFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanelCarrEfVend, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanelCarrEfVend, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LblDesconto, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDesconto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LblValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnDesconto)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanelEfeVend, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jPanelDadosVend, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbFormaPagamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbFormaPagamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbFormaPagamentoActionPerformed

    private void BtnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnVoltarActionPerformed
        this.doDefaultCloseAction();
        TelaPrincipal.MenuPrincipal.setVisible(true);
    }//GEN-LAST:event_BtnVoltarActionPerformed

    private void tblItensVendaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblItensVendaMouseClicked
        int linha = tblItensVenda.getSelectedRow();
        nomeProduto = (String) tblItensVenda.getModel().getValueAt(linha, 0);  //(VendaItem) tblItens.getModel().getValueAt(linha, 3);
     
    }//GEN-LAST:event_tblItensVendaMouseClicked

    private void BtnFinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnFinalActionPerformed
        try {
            extraiCampos();
            if(JOptionPane.showConfirmDialog(rootPane, "Deseja realmente Venda?") == 0){
                preencheObjeto();
                
                if(dao.Salvar(entidade)){
                    JOptionPane.showMessageDialog(rootPane, "Venda Concluída com Sucesso!");
                    preencheCampos();
                }
                else JOptionPane.showMessageDialog(rootPane, "Erro durante a execução");
                
            } else JOptionPane.showMessageDialog(rootPane, "Operação cancelada!");
        } catch (ParseException ex) {
           ex.printStackTrace();
        }
        
    }           

    private void preencheObjeto() {
        try {
            
            ArrayList<Cliente> listaClientes = daoCliente.listarClientes();
            for(Cliente novo: listaClientes){
                if(novo.getNome().equals(cmbCliente.getSelectedItem()))
                    entidade.setCliente(novo);
            }
            
            SimpleDateFormat format = new SimpleDateFormat("dd/MM/yyyy");
            java.sql.Date data = new java.sql.Date(format.parse(txtdata.getText()).getTime());
            entidade.setData(data);
        } catch (ParseException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_BtnFinalActionPerformed

    private void btnAdicionarItensActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarItensActionPerformed
        Produto produtoSelecionado = null;

        ArrayList<Produto> listaProdutos = daoProduto.listarProdutos();
        for(Produto novo: listaProdutos){
            if(novo.getNome().equals(cmbProduto.getSelectedItem()))
                produtoSelecionado = novo;
        }
        int quantidade = (Integer)spinQuantidade.getValue();
        
        ItensVenda item = new ItensVenda(produtoSelecionado,quantidade);
       
        if(!listaCompras.contains(item)){
            listaCompras.add(item);
            this.valorTotal= valorTotal.add(item.getProduto().getPrecoUnitario().multiply(new BigDecimal(item.getQuantidade())));
        }
        
        preencheTabela();
        txtValorTotal.setText(String.valueOf(valorTotal));
        
    }//GEN-LAST:event_btnAdicionarItensActionPerformed

    private void btnRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverActionPerformed
        if(JOptionPane.showConfirmDialog(rootPane, "Deseja realmente remover o item?") == 0){
            
            for(ItensVenda itens: listaCompras){
                if(itens.getProduto().getNome().equals(nomeProduto)){
                    this.valorTotal = valorTotal.subtract(itens.getProduto().getPrecoUnitario().multiply(new BigDecimal(itens.getQuantidade())));
                    txtValorTotal.setText(valorTotal.toString());
                    listaCompras.remove(itens);
                    preencheTabela();
                    JOptionPane.showMessageDialog(rootPane, "Item removido com sucesso!");
                }
            }
        }
    }//GEN-LAST:event_btnRemoverActionPerformed

    private void btnDescontoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDescontoActionPerformed
        if(!txtDesconto.equals("")){
            BigDecimal novoValor = new BigDecimal(txtValorTotal.getText());
            novoValor = novoValor.subtract(novoValor.multiply(new BigDecimal(txtDesconto.getText()).divide(new BigDecimal("100"))));
            txtValorTotal.setText(novoValor.toString());
        }
    }//GEN-LAST:event_btnDescontoActionPerformed

    private void BtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCancelarActionPerformed
        if(JOptionPane.showConfirmDialog(rootPane, "Deseja realmente cancelar a Operação?") == 0){
            this.doDefaultCloseAction();
        }
    }//GEN-LAST:event_BtnCancelarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCancelar;
    private javax.swing.JButton BtnFinal;
    private javax.swing.JButton BtnVoltar;
    private javax.swing.JLabel LblCliente;
    private javax.swing.JLabel LblData;
    private javax.swing.JLabel LblDesconto;
    private javax.swing.JLabel LblFormaPagamento;
    private javax.swing.JLabel LblProduto;
    private javax.swing.JLabel LblQuantidade;
    private javax.swing.JLabel LblValorTotal;
    private javax.swing.JButton btnAdicionarItens;
    private javax.swing.JButton btnDesconto;
    private javax.swing.JButton btnRemover;
    private javax.swing.JComboBox cmbCliente;
    private javax.swing.JComboBox cmbFormaPagamento;
    private javax.swing.JComboBox cmbProduto;
    private javax.swing.JPanel jPanelCarrEfVend;
    private javax.swing.JPanel jPanelDadosVend;
    private javax.swing.JPanel jPanelEfeVend;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner spinQuantidade;
    private javax.swing.JTable tblItensVenda;
    private javax.swing.JTextField txtDesconto;
    private javax.swing.JTextField txtValorTotal;
    private javax.swing.JFormattedTextField txtdata;
    // End of variables declaration//GEN-END:variables

    private void carregarCombo() {
       daoCliente = new ClienteDAO();
       ArrayList<Cliente> listaCliente = daoCliente.listarClientes();
       cmbCliente.addItem("Selecione");
       for(Cliente novo: listaCliente){
           cmbCliente.addItem(novo.getNome());
       }
        
        daoProduto = new ProdutoDAO();
        ArrayList<Produto> listaProdutos = daoProduto.listarProdutos();
        cmbProduto.addItem("Selecione");
        for(Produto produto: listaProdutos){
            cmbProduto.addItem(produto.getNome());
        }
    }

    private void preencheCampos() {
        txtdata.setText(df.format(entidade.getData())); 
        cmbFormaPagamento.setSelectedItem(entidade.getFormaPagamento());
        cmbCliente.setSelectedItem(entidade.getCliente());
        txtValorTotal.setText(entidade.getValorTotal().toString());
        txtDesconto.setText(entidade.getDesconto().toString());
    }

    private void preencheCamposItem() {
        spinQuantidade.setValue(itemSelecionado.getQuantidade());
        cmbProduto.setSelectedItem(itemSelecionado.getProduto().getNome());
    }

    void setEntidade(Venda entidade) {
        this.entidade = entidade;
        preencheCampos();
    }
    
    private void preencheTabela(){
        DefaultTableModel itens = new DefaultTableModel();
        
        itens.addColumn("Produto");
        itens.addColumn("Quantidade");
        
        for(ItensVenda i : listaCompras){
            Vector valor = new Vector();
            valor.add(i.getProduto().getNome());
            valor.add(i.getQuantidade());
            valor.add(i);
            itens.addRow(valor);
        }
        tblItensVenda.setModel(itens);
    }

    private void extraiCampos() throws ParseException {
        entidade = new Venda();
        if(!txtdata.getText().equals("")){
            SimpleDateFormat format = new SimpleDateFormat("dd/MM/yyyy");
            java.sql.Date data = new java.sql.Date(format.parse(txtdata.getText()).getTime());
            System.out.println("Data Formatada: "+data);
            entidade.setData(data);
        }
      
        ArrayList<Cliente> listaClientes = daoCliente.listarClientes();
        for(Cliente cliente: listaClientes){
            if(cmbProduto.getSelectedItem().equals(cliente.getNome()))
                entidade.setCliente(cliente);
        }
        
        String pagamento = "";
        switch(cmbFormaPagamento.getSelectedIndex()){
            case 1: {
                pagamento = "Dinheiro";
                break;
            }
            case 2:{
                pagamento = "Débito";
                break;
            }
            case 3:{
                pagamento = "Crédito";
                break;
            }
        }
        entidade.setFormaPagamento(pagamento);
        BigDecimal valorDesconto = new BigDecimal("0.00");
        entidade.setDesconto(valorDesconto);
        entidade.setValorTotal(this.valorTotal);
        entidade.setItens(listaCompras);
    }
}
