/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.ifnmg.psc.Apresentacao;

/**
 *
 * @author thais
 */
public class TelaEfetuarCompras extends javax.swing.JInternalFrame {

    /**
     * Creates new form TelaGerenciamentoCompras
     */
    public TelaEfetuarCompras() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelCarrGerenComp = new javax.swing.JPanel();
        PanelDadosCompra = new javax.swing.JPanel();
        LblForncedor = new javax.swing.JLabel();
        CBXFornecedor = new javax.swing.JComboBox();
        LblData = new javax.swing.JLabel();
        Txtdata = new javax.swing.JFormattedTextField();
        PanelCompras = new javax.swing.JPanel();
        LblProdutos = new javax.swing.JLabel();
        LblQuantidade = new javax.swing.JLabel();
        CBXProduto = new javax.swing.JComboBox();
        SpinnerQuantidade = new javax.swing.JSpinner();
        BtnAdicionar = new javax.swing.JButton();
        BtnEncaminhar = new javax.swing.JButton();
        BtnVoltar = new javax.swing.JButton();
        BtnCancelar = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        MenuGerenciar = new javax.swing.JMenu();
        MenuItemFuncionarios = new javax.swing.JMenuItem();
        MenuItemClientes = new javax.swing.JMenuItem();
        MenuItemVendas = new javax.swing.JMenuItem();
        MenuItemProdutos = new javax.swing.JMenuItem();
        MenuItemCompras = new javax.swing.JMenuItem();
        MenuItemEntregas = new javax.swing.JMenuItem();
        MenuItemVeiculos = new javax.swing.JMenuItem();
        MenuRelatorios = new javax.swing.JMenu();

        PanelCarrGerenComp.setBorder(javax.swing.BorderFactory.createTitledBorder("Carrinho de compras"));

        javax.swing.GroupLayout PanelCarrGerenCompLayout = new javax.swing.GroupLayout(PanelCarrGerenComp);
        PanelCarrGerenComp.setLayout(PanelCarrGerenCompLayout);
        PanelCarrGerenCompLayout.setHorizontalGroup(
            PanelCarrGerenCompLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 386, Short.MAX_VALUE)
        );
        PanelCarrGerenCompLayout.setVerticalGroup(
            PanelCarrGerenCompLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        PanelDadosCompra.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados da compra"));

        LblForncedor.setText("Fornecedor:");

        CBXFornecedor.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione", "Item 2", "Item 3", "Item 4" }));
        CBXFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBXFornecedorActionPerformed(evt);
            }
        });

        LblData.setText("Data:");

        Txtdata.setText("       /  /");

        javax.swing.GroupLayout PanelDadosCompraLayout = new javax.swing.GroupLayout(PanelDadosCompra);
        PanelDadosCompra.setLayout(PanelDadosCompraLayout);
        PanelDadosCompraLayout.setHorizontalGroup(
            PanelDadosCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDadosCompraLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelDadosCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LblData, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LblForncedor, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(PanelDadosCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Txtdata, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CBXFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(63, Short.MAX_VALUE))
        );
        PanelDadosCompraLayout.setVerticalGroup(
            PanelDadosCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelDadosCompraLayout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addGroup(PanelDadosCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblData, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Txtdata, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelDadosCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblForncedor, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CBXFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52))
        );

        PanelCompras.setBorder(javax.swing.BorderFactory.createTitledBorder("Efetuar Compras"));

        LblProdutos.setText("Produto:");

        LblQuantidade.setText("Quantidade:");

        CBXProduto.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione", "Item 2", "Item 3", "Item 4" }));

        BtnAdicionar.setText("Adicionar");

        javax.swing.GroupLayout PanelComprasLayout = new javax.swing.GroupLayout(PanelCompras);
        PanelCompras.setLayout(PanelComprasLayout);
        PanelComprasLayout.setHorizontalGroup(
            PanelComprasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelComprasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelComprasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(BtnAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PanelComprasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(PanelComprasLayout.createSequentialGroup()
                            .addComponent(LblQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(SpinnerQuantidade))
                        .addComponent(LblProdutos, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(PanelComprasLayout.createSequentialGroup()
                            .addGap(108, 108, 108)
                            .addComponent(CBXProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        PanelComprasLayout.setVerticalGroup(
            PanelComprasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelComprasLayout.createSequentialGroup()
                .addGroup(PanelComprasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelComprasLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(CBXProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PanelComprasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LblQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SpinnerQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(PanelComprasLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(LblProdutos, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(BtnAdicionar)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        BtnEncaminhar.setText("Encaminhar Pedido");

        BtnVoltar.setText("Voltar");

        BtnCancelar.setText("Cancelar");

        MenuGerenciar.setText("Gerenciar");

        MenuItemFuncionarios.setText("Funcionários");
        MenuItemFuncionarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemFuncionariosActionPerformed(evt);
            }
        });
        MenuGerenciar.add(MenuItemFuncionarios);

        MenuItemClientes.setText("Clientes");
        MenuItemClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemClientesActionPerformed(evt);
            }
        });
        MenuGerenciar.add(MenuItemClientes);

        MenuItemVendas.setText("Vendas");
        MenuItemVendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemVendasActionPerformed(evt);
            }
        });
        MenuGerenciar.add(MenuItemVendas);

        MenuItemProdutos.setText("Produtos");
        MenuItemProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemProdutosActionPerformed(evt);
            }
        });
        MenuGerenciar.add(MenuItemProdutos);

        MenuItemCompras.setText("Compras");
        MenuItemCompras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemComprasActionPerformed(evt);
            }
        });
        MenuGerenciar.add(MenuItemCompras);

        MenuItemEntregas.setText("Entregas");
        MenuItemEntregas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemEntregasActionPerformed(evt);
            }
        });
        MenuGerenciar.add(MenuItemEntregas);

        MenuItemVeiculos.setText("Veículos");
        MenuItemVeiculos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemVeiculosActionPerformed(evt);
            }
        });
        MenuGerenciar.add(MenuItemVeiculos);

        jMenuBar1.add(MenuGerenciar);

        MenuRelatorios.setText("Relatórios");
        jMenuBar1.add(MenuRelatorios);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PanelDadosCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BtnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BtnEncaminhar, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(PanelCarrGerenComp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(22, 22, 22)
                    .addComponent(PanelCompras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(459, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(218, 218, 218)
                        .addComponent(PanelDadosCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(PanelCarrGerenComp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnVoltar)
                    .addComponent(BtnCancelar)
                    .addComponent(BtnEncaminhar))
                .addGap(0, 26, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(22, 22, 22)
                    .addComponent(PanelCompras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(244, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CBXFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBXFornecedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CBXFornecedorActionPerformed

    private void MenuItemProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemProdutosActionPerformed
       TelaGerenciarProduto telaProduto = new TelaGerenciarProduto();
        this.add(telaProduto);
        telaProduto.setVisible(true);
    }//GEN-LAST:event_MenuItemProdutosActionPerformed

    private void MenuItemFuncionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemFuncionariosActionPerformed
       TelaGerenciarFuncionarios telaFuncionarios = new TelaGerenciarFuncionarios();
        this.add(telaFuncionarios);
        telaFuncionarios.setVisible(true);
    }//GEN-LAST:event_MenuItemFuncionariosActionPerformed

    private void MenuItemClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemClientesActionPerformed
         TelaGerenciarClientes telaClientes = new TelaGerenciarClientes();
        this.add(telaClientes);
        telaClientes.setVisible(true);
    }//GEN-LAST:event_MenuItemClientesActionPerformed

    private void MenuItemVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemVendasActionPerformed
        TelaGerenciamentoVendas telaVendas = new TelaGerenciamentoVendas();
        this.add(telaVendas);
        telaVendas.setVisible(true);
    }//GEN-LAST:event_MenuItemVendasActionPerformed

    private void MenuItemComprasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemComprasActionPerformed
        TelaEfetuarCompras telaCompras = new TelaEfetuarCompras();
        this.add(telaCompras);
        telaCompras.setVisible(true);
    }//GEN-LAST:event_MenuItemComprasActionPerformed

    private void MenuItemEntregasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemEntregasActionPerformed
       TelaEfetuarEntrega telaEntregas = new TelaEfetuarEntrega();
        this.add(telaEntregas);
        telaEntregas.setVisible(true);
    }//GEN-LAST:event_MenuItemEntregasActionPerformed

    private void MenuItemVeiculosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemVeiculosActionPerformed
         TelaGerenciarVeiculos telaVeiculos = new TelaGerenciarVeiculos();
        this.add(telaVeiculos);
        telaVeiculos.setVisible(true);
    }//GEN-LAST:event_MenuItemVeiculosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAdicionar;
    private javax.swing.JButton BtnCancelar;
    private javax.swing.JButton BtnEncaminhar;
    private javax.swing.JButton BtnVoltar;
    private javax.swing.JComboBox CBXFornecedor;
    private javax.swing.JComboBox CBXProduto;
    private javax.swing.JLabel LblData;
    private javax.swing.JLabel LblForncedor;
    private javax.swing.JLabel LblProdutos;
    private javax.swing.JLabel LblQuantidade;
    private javax.swing.JMenu MenuGerenciar;
    private javax.swing.JMenuItem MenuItemClientes;
    private javax.swing.JMenuItem MenuItemCompras;
    private javax.swing.JMenuItem MenuItemEntregas;
    private javax.swing.JMenuItem MenuItemFuncionarios;
    private javax.swing.JMenuItem MenuItemProdutos;
    private javax.swing.JMenuItem MenuItemVeiculos;
    private javax.swing.JMenuItem MenuItemVendas;
    private javax.swing.JMenu MenuRelatorios;
    private javax.swing.JPanel PanelCarrGerenComp;
    private javax.swing.JPanel PanelCompras;
    private javax.swing.JPanel PanelDadosCompra;
    private javax.swing.JSpinner SpinnerQuantidade;
    private javax.swing.JFormattedTextField Txtdata;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
