/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.ifnmg.psc.Apresentacao;

/**
 *
 * @author thais
 */
public class TelaCadastroClientes extends javax.swing.JInternalFrame {

    /**
     * Creates new form TelaCadastroClientes
     */
    public TelaCadastroClientes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelCadastroClient = new javax.swing.JPanel();
        jCartTrabCliente = new javax.swing.JLabel();
        jCPFCliente = new javax.swing.JLabel();
        jRGCliente = new javax.swing.JLabel();
        jSexoCliente = new javax.swing.JLabel();
        jCBSexoCliente = new javax.swing.JComboBox();
        jDatNascCliente = new javax.swing.JLabel();
        jFTxtDataNascCliente = new javax.swing.JFormattedTextField();
        jTelefoneCliente = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jEnderCliente = new javax.swing.JLabel();
        jTxtEnderCliente = new javax.swing.JTextField();
        jNumeroCliente = new javax.swing.JLabel();
        jComplementoCliente = new javax.swing.JLabel();
        jBairroCliente = new javax.swing.JLabel();
        jCityCliente = new javax.swing.JLabel();
        jTxtNumCliente = new javax.swing.JTextField();
        jTxtCityCliente = new javax.swing.JTextField();
        jTxtCompleCliente = new javax.swing.JTextField();
        jTxtNomeCliente = new javax.swing.JTextField();
        jTxtCPFCliente = new javax.swing.JTextField();
        jTxtRGCliente = new javax.swing.JTextField();
        jTxtCatTrabCliente = new javax.swing.JTextField();
        jFTxtTelCliente = new javax.swing.JFormattedTextField();
        jNomeCliente = new javax.swing.JLabel();
        jTxtBairrCliente = new javax.swing.JTextField();
        jBtnVoltar = new javax.swing.JButton();
        jBtnSalvar = new javax.swing.JButton();
        jBtnExcluir = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuGerenciar = new javax.swing.JMenu();
        jMenuItemFunc = new javax.swing.JMenuItem();
        jMenuItemcli = new javax.swing.JMenuItem();
        jMenuItemVend = new javax.swing.JMenuItem();
        jMenuItemProd = new javax.swing.JMenuItem();
        jMenuItemComp = new javax.swing.JMenuItem();
        jMenuItemEst = new javax.swing.JMenuItem();
        jMenuItemEntr = new javax.swing.JMenuItem();
        jMenuItemVeic = new javax.swing.JMenuItem();
        jMenuRelatorio = new javax.swing.JMenu();

        jPanelCadastroClient.setBorder(javax.swing.BorderFactory.createTitledBorder("Cadastro de Cliente"));

        jCartTrabCliente.setText("Carteira de Trabalho:");

        jCPFCliente.setText("CPF:");

        jRGCliente.setText("RG:");

        jSexoCliente.setText("Sexo:");

        jCBSexoCliente.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione", "Masculino", "Feminino", "Outro" }));
        jCBSexoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBSexoClienteActionPerformed(evt);
            }
        });

        jDatNascCliente.setText("Data Nascimento: ");

        jFTxtDataNascCliente.setText("   / /");
        jFTxtDataNascCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFTxtDataNascClienteActionPerformed(evt);
            }
        });

        jTelefoneCliente.setText("Telefone:");

        jEnderCliente.setText("Rua/Av:");

        jNumeroCliente.setText("Número:");

        jComplementoCliente.setText("Complemento:");

        jBairroCliente.setText("Bairro:");

        jCityCliente.setText("Cidade:");

        jTxtNumCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtNumClienteActionPerformed(evt);
            }
        });

        jTxtCPFCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtCPFClienteActionPerformed(evt);
            }
        });

        jFTxtTelCliente.setText("( )");

        javax.swing.GroupLayout jPanelCadastroClientLayout = new javax.swing.GroupLayout(jPanelCadastroClient);
        jPanelCadastroClient.setLayout(jPanelCadastroClientLayout);
        jPanelCadastroClientLayout.setHorizontalGroup(
            jPanelCadastroClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCadastroClientLayout.createSequentialGroup()
                .addGroup(jPanelCadastroClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCadastroClientLayout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(jSeparator1))
                    .addGroup(jPanelCadastroClientLayout.createSequentialGroup()
                        .addGroup(jPanelCadastroClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelCadastroClientLayout.createSequentialGroup()
                                .addGroup(jPanelCadastroClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanelCadastroClientLayout.createSequentialGroup()
                                        .addComponent(jEnderCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(45, 45, 45)
                                        .addGroup(jPanelCadastroClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTxtEnderCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanelCadastroClientLayout.createSequentialGroup()
                                                .addGroup(jPanelCadastroClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jTxtNumCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jTxtCompleCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(56, 56, 56)
                                                .addGroup(jPanelCadastroClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jBairroCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jCityCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                    .addComponent(jComplementoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jTxtCityCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelCadastroClientLayout.createSequentialGroup()
                                .addGroup(jPanelCadastroClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanelCadastroClientLayout.createSequentialGroup()
                                        .addComponent(jCPFCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(24, 24, 24)
                                        .addGroup(jPanelCadastroClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTxtNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTxtCPFCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanelCadastroClientLayout.createSequentialGroup()
                                        .addGroup(jPanelCadastroClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jCartTrabCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jDatNascCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanelCadastroClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jFTxtDataNascCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTxtCatTrabCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(63, 63, 63)
                                .addGroup(jPanelCadastroClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTelefoneCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanelCadastroClientLayout.createSequentialGroup()
                                        .addGroup(jPanelCadastroClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanelCadastroClientLayout.createSequentialGroup()
                                                .addComponent(jRGCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(9, 9, 9))
                                            .addComponent(jSexoCliente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanelCadastroClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanelCadastroClientLayout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addGroup(jPanelCadastroClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jCBSexoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jFTxtTelCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCadastroClientLayout.createSequentialGroup()
                                                .addGap(17, 17, 17)
                                                .addComponent(jTxtRGCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                            .addComponent(jNumeroCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 280, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelCadastroClientLayout.setVerticalGroup(
            jPanelCadastroClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCadastroClientLayout.createSequentialGroup()
                .addGroup(jPanelCadastroClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCadastroClientLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jTxtRGCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelCadastroClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCBSexoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSexoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(13, 13, 13)
                        .addGroup(jPanelCadastroClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTelefoneCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanelCadastroClientLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jFTxtTelCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(109, 109, 109))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCadastroClientLayout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(jCPFCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCartTrabCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jDatNascCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCadastroClientLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanelCadastroClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTxtNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jRGCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTxtCPFCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTxtCatTrabCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jFTxtDataNascCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(73, 73, 73)))
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCadastroClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jEnderCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtEnderCliente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(jPanelCadastroClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCadastroClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTxtNumCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jBairroCliente))
                    .addGroup(jPanelCadastroClientLayout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jNumeroCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCadastroClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComplementoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtCompleCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCityCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTxtCityCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jNomeCliente.setText("Nome:");

        jTxtBairrCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtBairrClienteActionPerformed(evt);
            }
        });

        jBtnVoltar.setText("Voltar");

        jBtnSalvar.setText("Salvar");

        jBtnExcluir.setText("Excluir");

        jMenuGerenciar.setText("Gerenciar");

        jMenuItemFunc.setText("Funcionários");
        jMenuGerenciar.add(jMenuItemFunc);

        jMenuItemcli.setText("Clientes");
        jMenuGerenciar.add(jMenuItemcli);

        jMenuItemVend.setText("Vendas");
        jMenuGerenciar.add(jMenuItemVend);

        jMenuItemProd.setText("Produtos");
        jMenuGerenciar.add(jMenuItemProd);

        jMenuItemComp.setText("Compras");
        jMenuGerenciar.add(jMenuItemComp);

        jMenuItemEst.setText("Estoque");
        jMenuGerenciar.add(jMenuItemEst);

        jMenuItemEntr.setText("Entregas");
        jMenuGerenciar.add(jMenuItemEntr);

        jMenuItemVeic.setText("Veículos");
        jMenuGerenciar.add(jMenuItemVeic);

        jMenuBar1.add(jMenuGerenciar);

        jMenuRelatorio.setText("Relatórios");
        jMenuBar1.add(jMenuRelatorio);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jBtnVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 530, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jBtnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(72, 72, 72)
                                .addComponent(jBtnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jTxtBairrCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(308, 308, 308))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(4, 4, 4)
                    .addComponent(jPanelCadastroClient, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 230, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jTxtBairrCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(59, 59, 59)
                        .addComponent(jBtnVoltar)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jBtnSalvar)
                            .addComponent(jBtnExcluir))
                        .addGap(21, 21, 21))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanelCadastroClient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(55, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCBSexoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBSexoClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCBSexoClienteActionPerformed

    private void jFTxtDataNascClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFTxtDataNascClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFTxtDataNascClienteActionPerformed

    private void jTxtNumClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtNumClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtNumClienteActionPerformed

    private void jTxtBairrClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtBairrClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtBairrClienteActionPerformed

    private void jTxtCPFClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtCPFClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtCPFClienteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jBairroCliente;
    private javax.swing.JButton jBtnExcluir;
    private javax.swing.JButton jBtnSalvar;
    private javax.swing.JButton jBtnVoltar;
    private javax.swing.JComboBox jCBSexoCliente;
    private javax.swing.JLabel jCPFCliente;
    private javax.swing.JLabel jCartTrabCliente;
    private javax.swing.JLabel jCityCliente;
    private javax.swing.JLabel jComplementoCliente;
    private javax.swing.JLabel jDatNascCliente;
    private javax.swing.JLabel jEnderCliente;
    private javax.swing.JFormattedTextField jFTxtDataNascCliente;
    private javax.swing.JFormattedTextField jFTxtTelCliente;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuGerenciar;
    private javax.swing.JMenuItem jMenuItemComp;
    private javax.swing.JMenuItem jMenuItemEntr;
    private javax.swing.JMenuItem jMenuItemEst;
    private javax.swing.JMenuItem jMenuItemFunc;
    private javax.swing.JMenuItem jMenuItemProd;
    private javax.swing.JMenuItem jMenuItemVeic;
    private javax.swing.JMenuItem jMenuItemVend;
    private javax.swing.JMenuItem jMenuItemcli;
    private javax.swing.JMenu jMenuRelatorio;
    private javax.swing.JLabel jNomeCliente;
    private javax.swing.JLabel jNumeroCliente;
    private javax.swing.JPanel jPanelCadastroClient;
    private javax.swing.JLabel jRGCliente;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel jSexoCliente;
    private javax.swing.JLabel jTelefoneCliente;
    private javax.swing.JTextField jTxtBairrCliente;
    private javax.swing.JTextField jTxtCPFCliente;
    private javax.swing.JTextField jTxtCatTrabCliente;
    private javax.swing.JTextField jTxtCityCliente;
    private javax.swing.JTextField jTxtCompleCliente;
    private javax.swing.JTextField jTxtEnderCliente;
    private javax.swing.JTextField jTxtNomeCliente;
    private javax.swing.JTextField jTxtNumCliente;
    private javax.swing.JTextField jTxtRGCliente;
    // End of variables declaration//GEN-END:variables
}
