/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.ifnmg.psc.Apresentacao;

/**
 *
 * @author thais
 */
public class TelaCadastroUsuario extends javax.swing.JInternalFrame {

    /**
     * Creates new form TelaCadastroUsuario
     */
    public TelaCadastroUsuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelCadastroUsuario = new javax.swing.JPanel();
        jNomeFunc = new javax.swing.JLabel();
        jLoginUsu = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jTxtLoginUsu = new javax.swing.JTextField();
        jSenhaUsu = new javax.swing.JLabel();
        jConfSenha = new javax.swing.JLabel();
        jPassw = new javax.swing.JPasswordField();
        jPasswConf = new javax.swing.JPasswordField();
        jCBFunc = new javax.swing.JComboBox();
        jBtnVolt = new javax.swing.JButton();
        jBtnCancel = new javax.swing.JButton();
        jBtnSalv = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jGerenc = new javax.swing.JMenu();
        jFunc = new javax.swing.JMenuItem();
        jClient = new javax.swing.JMenuItem();
        jVend = new javax.swing.JMenuItem();
        jProd = new javax.swing.JMenuItem();
        jComp = new javax.swing.JMenuItem();
        jEstoq = new javax.swing.JMenuItem();
        jEntreg = new javax.swing.JMenuItem();
        jVeic = new javax.swing.JMenuItem();
        jRelat = new javax.swing.JMenu();

        jPanelCadastroUsuario.setBorder(javax.swing.BorderFactory.createTitledBorder("Cadastro de Usuário"));

        jNomeFunc.setText("Funcionário:");

        jLoginUsu.setText("Login:");

        jTxtLoginUsu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtLoginUsuActionPerformed(evt);
            }
        });

        jSenhaUsu.setText("Senha:");

        jConfSenha.setText("Confirmar senha:");

        jCBFunc.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione", "Item 2", "Item 3", "Item 4" }));
        jCBFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBFuncActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelCadastroUsuarioLayout = new javax.swing.GroupLayout(jPanelCadastroUsuario);
        jPanelCadastroUsuario.setLayout(jPanelCadastroUsuarioLayout);
        jPanelCadastroUsuarioLayout.setHorizontalGroup(
            jPanelCadastroUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCadastroUsuarioLayout.createSequentialGroup()
                .addGroup(jPanelCadastroUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCadastroUsuarioLayout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(jSeparator1))
                    .addGroup(jPanelCadastroUsuarioLayout.createSequentialGroup()
                        .addGroup(jPanelCadastroUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanelCadastroUsuarioLayout.createSequentialGroup()
                                .addGroup(jPanelCadastroUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jConfSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jSenhaUsu, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanelCadastroUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jPassw, javax.swing.GroupLayout.DEFAULT_SIZE, 318, Short.MAX_VALUE)
                                    .addComponent(jPasswConf)))
                            .addGroup(jPanelCadastroUsuarioLayout.createSequentialGroup()
                                .addGroup(jPanelCadastroUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLoginUsu, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jNomeFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(44, 44, 44)
                                .addGroup(jPanelCadastroUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jCBFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTxtLoginUsu, javax.swing.GroupLayout.DEFAULT_SIZE, 318, Short.MAX_VALUE))))
                        .addGap(0, 128, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelCadastroUsuarioLayout.setVerticalGroup(
            jPanelCadastroUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCadastroUsuarioLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanelCadastroUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jNomeFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCBFunc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelCadastroUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLoginUsu, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtLoginUsu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelCadastroUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSenhaUsu, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPassw, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanelCadastroUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jConfSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPasswConf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(99, 99, 99))
        );

        jBtnVolt.setText("Voltar");

        jBtnCancel.setText("Cancelar");

        jBtnSalv.setText("Salvar");

        jGerenc.setText("Gerenciar");

        jFunc.setText("Funcionários");
        jGerenc.add(jFunc);

        jClient.setText("Clientes");
        jGerenc.add(jClient);

        jVend.setText("Vendas");
        jGerenc.add(jVend);

        jProd.setText("Produtos");
        jGerenc.add(jProd);

        jComp.setText("Compras");
        jGerenc.add(jComp);

        jEstoq.setText("Estoque");
        jGerenc.add(jEstoq);

        jEntreg.setText("Entregas");
        jGerenc.add(jEntreg);

        jVeic.setText("Veículos");
        jGerenc.add(jVeic);

        jMenuBar1.add(jGerenc);

        jRelat.setText("Relatórios");
        jMenuBar1.add(jRelat);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jBtnVolt, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 274, Short.MAX_VALUE)
                .addComponent(jBtnCancel)
                .addGap(77, 77, 77)
                .addComponent(jBtnSalv, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanelCadastroUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(299, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnVolt)
                    .addComponent(jBtnCancel)
                    .addComponent(jBtnSalv))
                .addGap(30, 30, 30))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanelCadastroUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(62, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTxtLoginUsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtLoginUsuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtLoginUsuActionPerformed

    private void jCBFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBFuncActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCBFuncActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnCancel;
    private javax.swing.JButton jBtnSalv;
    private javax.swing.JButton jBtnVolt;
    private javax.swing.JComboBox jCBFunc;
    private javax.swing.JMenuItem jClient;
    private javax.swing.JMenuItem jComp;
    private javax.swing.JLabel jConfSenha;
    private javax.swing.JMenuItem jEntreg;
    private javax.swing.JMenuItem jEstoq;
    private javax.swing.JMenuItem jFunc;
    private javax.swing.JMenu jGerenc;
    private javax.swing.JLabel jLoginUsu;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel jNomeFunc;
    private javax.swing.JPanel jPanelCadastroUsuario;
    private javax.swing.JPasswordField jPassw;
    private javax.swing.JPasswordField jPasswConf;
    private javax.swing.JMenuItem jProd;
    private javax.swing.JMenu jRelat;
    private javax.swing.JLabel jSenhaUsu;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTxtLoginUsu;
    private javax.swing.JMenuItem jVeic;
    private javax.swing.JMenuItem jVend;
    // End of variables declaration//GEN-END:variables
}
