/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.ifnmg.psc.Apresentacao;

import java.awt.BorderLayout;
import java.awt.Toolkit;
import java.beans.PropertyVetoException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JInternalFrame;

/**
 *
 * @author victor
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form PrincipalDesktop
     */
    public TelaPrincipal() {
        initComponents();
        this.setExtendedState(this.MAXIMIZED_BOTH); 
        setContentPane(DesktopPrincipal);
        //getContentPane().add(DesktopPrincipal);
        //this.PainelInternoPrincipal.setSize(DesktopPrincipal.getSize());
        //this.add(PainelInternoPrincipal, BorderLayout.CENTER);
        PainelInternoPrincipal.setVisible(true);
        PainelLateral.setVisible(true);
        //PainelLateral.setSize(DesktopPrincipal.getSize());
        getContentPane().add(PainelInternoPrincipal);
        getContentPane().add(PainelLateral, BorderLayout.EAST);
        //this.getContentPane().add(PainelLateral, BorderLayout);
        //setContentPane(PainelInternoPrincipal);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PainelInternoPrincipal = new javax.swing.JPanel();
        btnCliente = new javax.swing.JButton();
        btnCompras = new javax.swing.JButton();
        btnProdutos = new javax.swing.JButton();
        btnVendas = new javax.swing.JButton();
        PainelLateral = new javax.swing.JPanel();
        PainelDadosUsuario = new javax.swing.JPanel();
        LblUsuarioLogado = new javax.swing.JLabel();
        LblFuncao = new javax.swing.JLabel();
        txtUsuarioLogado = new javax.swing.JTextField();
        txtFuncao = new javax.swing.JTextField();
        btnSair = new javax.swing.JButton();
        PainelCaixa = new javax.swing.JPanel();
        LblStatus = new javax.swing.JLabel();
        txtStatus = new javax.swing.JTextField();
        btnAbrirFechar = new javax.swing.JButton();
        DesktopPrincipal = new javax.swing.JDesktopPane();
        MenuPrincipal = new javax.swing.JMenuBar();
        menuGerenciar = new javax.swing.JMenu();
        menuItemClientes = new javax.swing.JMenuItem();
        MenuItemCompras = new javax.swing.JMenuItem();
        MenuItemEntrega = new javax.swing.JMenuItem();
        itemFornecedores = new javax.swing.JMenuItem();
        menuItemFuncionarios = new javax.swing.JMenuItem();
        menuItemProdutos = new javax.swing.JMenuItem();
        MenuItemVeiculo = new javax.swing.JMenuItem();
        menuItemVendas = new javax.swing.JMenuItem();
        menuRelatorios = new javax.swing.JMenu();
        menuRelatorioVendas = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        PainelInternoPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCliente.setText("Clientes");
        btnCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClienteActionPerformed(evt);
            }
        });
        PainelInternoPrincipal.add(btnCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 130, 70));

        btnCompras.setText("Compras");
        btnCompras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComprasActionPerformed(evt);
            }
        });
        PainelInternoPrincipal.add(btnCompras, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, 130, 70));

        btnProdutos.setText("Produtos");
        btnProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProdutosActionPerformed(evt);
            }
        });
        PainelInternoPrincipal.add(btnProdutos, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, 130, 70));

        btnVendas.setText("Vendas");
        btnVendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVendasActionPerformed(evt);
            }
        });
        PainelInternoPrincipal.add(btnVendas, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 190, 130, 70));

        getContentPane().add(PainelInternoPrincipal);
        PainelInternoPrincipal.setBounds(110, 100, 530, 280);

        PainelDadosUsuario.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados do usuário"));

        LblUsuarioLogado.setText("Usuário logado:");

        LblFuncao.setText("Função:");

        txtUsuarioLogado.setEditable(false);

        txtFuncao.setEditable(false);

        btnSair.setText("Sair");

        javax.swing.GroupLayout PainelDadosUsuarioLayout = new javax.swing.GroupLayout(PainelDadosUsuario);
        PainelDadosUsuario.setLayout(PainelDadosUsuarioLayout);
        PainelDadosUsuarioLayout.setHorizontalGroup(
            PainelDadosUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelDadosUsuarioLayout.createSequentialGroup()
                .addGroup(PainelDadosUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PainelDadosUsuarioLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PainelDadosUsuarioLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(PainelDadosUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(LblFuncao, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LblUsuarioLogado, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtFuncao, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                            .addComponent(txtUsuarioLogado))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PainelDadosUsuarioLayout.setVerticalGroup(
            PainelDadosUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelDadosUsuarioLayout.createSequentialGroup()
                .addComponent(LblUsuarioLogado, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtUsuarioLogado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(LblFuncao, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtFuncao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSair)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        PainelCaixa.setBorder(javax.swing.BorderFactory.createTitledBorder("Caixa"));

        LblStatus.setText("Status:");

        btnAbrirFechar.setText("Abrir/Fechar");

        javax.swing.GroupLayout PainelCaixaLayout = new javax.swing.GroupLayout(PainelCaixa);
        PainelCaixa.setLayout(PainelCaixaLayout);
        PainelCaixaLayout.setHorizontalGroup(
            PainelCaixaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelCaixaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAbrirFechar, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55))
            .addGroup(PainelCaixaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LblStatus)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(64, Short.MAX_VALUE))
        );
        PainelCaixaLayout.setVerticalGroup(
            PainelCaixaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelCaixaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PainelCaixaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnAbrirFechar)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout PainelLateralLayout = new javax.swing.GroupLayout(PainelLateral);
        PainelLateral.setLayout(PainelLateralLayout);
        PainelLateralLayout.setHorizontalGroup(
            PainelLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelLateralLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(PainelLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(PainelDadosUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PainelCaixa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        PainelLateralLayout.setVerticalGroup(
            PainelLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelLateralLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(PainelDadosUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(PainelCaixa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(77, Short.MAX_VALUE))
        );

        getContentPane().add(PainelLateral);
        PainelLateral.setBounds(660, 0, 320, 460);

        DesktopPrincipal.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        DesktopPrincipal.setDoubleBuffered(true);
        DesktopPrincipal.setMinimumSize(new java.awt.Dimension(600, 800));
        getContentPane().add(DesktopPrincipal);
        DesktopPrincipal.setBounds(0, 0, 980, 460);

        menuGerenciar.setText("Gerenciar");

        menuItemClientes.setText("Clientes");
        menuItemClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemClientesActionPerformed(evt);
            }
        });
        menuGerenciar.add(menuItemClientes);

        MenuItemCompras.setText("Compras");
        MenuItemCompras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemComprasActionPerformed(evt);
            }
        });
        menuGerenciar.add(MenuItemCompras);

        MenuItemEntrega.setText("Entregas");
        MenuItemEntrega.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemEntregaActionPerformed(evt);
            }
        });
        menuGerenciar.add(MenuItemEntrega);

        itemFornecedores.setText("Fornecedores");
        itemFornecedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemFornecedoresActionPerformed(evt);
            }
        });
        menuGerenciar.add(itemFornecedores);

        menuItemFuncionarios.setText("Funcionários");
        menuItemFuncionarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemFuncionariosActionPerformed(evt);
            }
        });
        menuGerenciar.add(menuItemFuncionarios);

        menuItemProdutos.setText("Produtos");
        menuItemProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemProdutosActionPerformed(evt);
            }
        });
        menuGerenciar.add(menuItemProdutos);

        MenuItemVeiculo.setText("Veículos");
        MenuItemVeiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemVeiculoActionPerformed(evt);
            }
        });
        menuGerenciar.add(MenuItemVeiculo);

        menuItemVendas.setText("Vendas");
        menuItemVendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemVendasActionPerformed(evt);
            }
        });
        menuGerenciar.add(menuItemVendas);

        MenuPrincipal.add(menuGerenciar);

        menuRelatorios.setText("Relatórios");

        menuRelatorioVendas.setText("Vendas");
        menuRelatorios.add(menuRelatorioVendas);

        MenuPrincipal.add(menuRelatorios);

        setJMenuBar(MenuPrincipal);

        setSize(new java.awt.Dimension(986, 520));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClienteActionPerformed
        abreInternalFrame(new TelaGerenciarClientes());
    }//GEN-LAST:event_btnClienteActionPerformed

    private void menuItemFuncionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemFuncionariosActionPerformed
        abreInternalFrame(new TelaGerenciarFuncionarios());
    }//GEN-LAST:event_menuItemFuncionariosActionPerformed

    private void menuItemClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemClientesActionPerformed
        abreInternalFrame(new TelaGerenciarClientes());
    }//GEN-LAST:event_menuItemClientesActionPerformed

    private void menuItemVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemVendasActionPerformed
        abreInternalFrame(new TelaGerenciamentoVendas());
    }//GEN-LAST:event_menuItemVendasActionPerformed

    private void menuItemProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemProdutosActionPerformed
        abreInternalFrame(new TelaGerenciarProduto());
    }//GEN-LAST:event_menuItemProdutosActionPerformed

    private void MenuItemComprasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemComprasActionPerformed
        abreInternalFrame(new TelaEfetuarCompras());
    }//GEN-LAST:event_MenuItemComprasActionPerformed

    private void MenuItemEntregaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemEntregaActionPerformed
        abreInternalFrame(new TelaEfetuarEntrega());
    }//GEN-LAST:event_MenuItemEntregaActionPerformed

    private void MenuItemVeiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemVeiculoActionPerformed
        abreInternalFrame(new TelaGerenciarVeiculos());
    }//GEN-LAST:event_MenuItemVeiculoActionPerformed

    private void btnComprasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComprasActionPerformed
        abreInternalFrame(new TelaEfetuarCompras());
    }//GEN-LAST:event_btnComprasActionPerformed

    private void btnProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProdutosActionPerformed
        abreInternalFrame(new TelaGerenciarProduto());
    }//GEN-LAST:event_btnProdutosActionPerformed

    private void btnVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVendasActionPerformed
        abreInternalFrame(new TelaEfetuarVenda());
    }//GEN-LAST:event_btnVendasActionPerformed

    private void itemFornecedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemFornecedoresActionPerformed
        abreInternalFrame(new TelaGerenciarFornecedores());
    }//GEN-LAST:event_itemFornecedoresActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JDesktopPane DesktopPrincipal;
    private javax.swing.JLabel LblFuncao;
    private javax.swing.JLabel LblStatus;
    private javax.swing.JLabel LblUsuarioLogado;
    private javax.swing.JMenuItem MenuItemCompras;
    private javax.swing.JMenuItem MenuItemEntrega;
    private javax.swing.JMenuItem MenuItemVeiculo;
    public static javax.swing.JMenuBar MenuPrincipal;
    private javax.swing.JPanel PainelCaixa;
    private javax.swing.JPanel PainelDadosUsuario;
    public static javax.swing.JPanel PainelInternoPrincipal;
    public static javax.swing.JPanel PainelLateral;
    private javax.swing.JButton btnAbrirFechar;
    private javax.swing.JButton btnCliente;
    private javax.swing.JButton btnCompras;
    private javax.swing.JButton btnProdutos;
    private javax.swing.JButton btnSair;
    private javax.swing.JButton btnVendas;
    private javax.swing.JMenuItem itemFornecedores;
    private javax.swing.JMenu menuGerenciar;
    private javax.swing.JMenuItem menuItemClientes;
    private javax.swing.JMenuItem menuItemFuncionarios;
    private javax.swing.JMenuItem menuItemProdutos;
    private javax.swing.JMenuItem menuItemVendas;
    private javax.swing.JMenuItem menuRelatorioVendas;
    private javax.swing.JMenu menuRelatorios;
    private javax.swing.JTextField txtFuncao;
    private javax.swing.JTextField txtStatus;
    private javax.swing.JTextField txtUsuarioLogado;
    // End of variables declaration//GEN-END:variables
    
    public void abreInternalFrame(JInternalFrame frame) {
        frame.setVisible(true);
        DesktopPrincipal.add(frame, BorderLayout.CENTER);
        try {
            frame.setSelected(true);
            frame.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
        DesktopPrincipal.setVisible(true);
        PainelInternoPrincipal.setVisible(false); 
        PainelLateral.setVisible(false);
        frame.setSize(DesktopPrincipal.getSize());
        //frame.setLocation(0, 0);
        //this.add(DesktopPrincipal, BorderLayout.CENTER);
    }
}
