/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.ifnmg.psc.Apresentacao;

import br.edu.ifnmg.psc.Aplicacao.Fornecedor;
import br.edu.ifnmg.psc.Aplicacao.Produto;
import br.edu.ifnmg.psc.Aplicacao.ProdutoRepositorio;
import br.edu.ifnmg.psc.Excecao.ErroValidacao;
import br.edu.ifnmg.psc.Persistencia.ProdutoDAO;
import java.math.BigDecimal;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author thais
 */
public class TelaCadastroProdutos extends javax.swing.JInternalFrame {
    
    Produto produto = new Produto();
    ProdutoRepositorio dao = new ProdutoDAO();
    ProdutoRepositorio bd_Produto = GerenciadorReferencias.getProduto();
    TelaGerenciarProduto listagem;
    /**
     * Creates new form TelaCadastroProdutos
     */
    public TelaCadastroProdutos() {
        initComponents();
        carregarCombo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelCadastro = new javax.swing.JPanel();
        lblFornecedor = new javax.swing.JLabel();
        LblCodigo = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        LblPrecoUnitario = new javax.swing.JLabel();
        cmbFornecedor = new javax.swing.JComboBox();
        TxtPrecoUnitario = new javax.swing.JTextField();
        PainelDescricao = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescricao = new javax.swing.JTextArea();
        lblQuantidade = new javax.swing.JLabel();
        txtQuantidade = new javax.swing.JTextField();
        BtnVoltar = new javax.swing.JButton();
        BtnSalvar = new javax.swing.JButton();

        PanelCadastro.setBorder(javax.swing.BorderFactory.createTitledBorder("Cadastro de Produtos"));

        lblFornecedor.setText("Fornecedor:");

        LblCodigo.setText("Nome:");

        txtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeActionPerformed(evt);
            }
        });

        LblPrecoUnitario.setText("Preço Unitário:");

        cmbFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbFornecedorActionPerformed(evt);
            }
        });

        PainelDescricao.setBorder(javax.swing.BorderFactory.createTitledBorder("Descrição"));

        txtDescricao.setColumns(20);
        txtDescricao.setRows(5);
        jScrollPane1.setViewportView(txtDescricao);

        javax.swing.GroupLayout PainelDescricaoLayout = new javax.swing.GroupLayout(PainelDescricao);
        PainelDescricao.setLayout(PainelDescricaoLayout);
        PainelDescricaoLayout.setHorizontalGroup(
            PainelDescricaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelDescricaoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        PainelDescricaoLayout.setVerticalGroup(
            PainelDescricaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelDescricaoLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 13, Short.MAX_VALUE))
        );

        lblQuantidade.setText("Quantidade:");

        javax.swing.GroupLayout PanelCadastroLayout = new javax.swing.GroupLayout(PanelCadastro);
        PanelCadastro.setLayout(PanelCadastroLayout);
        PanelCadastroLayout.setHorizontalGroup(
            PanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelCadastroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PainelDescricao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelCadastroLayout.createSequentialGroup()
                        .addGroup(PanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LblPrecoUnitario, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LblCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(PanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNome)
                            .addComponent(TxtPrecoUnitario, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(51, 51, 51)
                        .addGroup(PanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(PanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cmbFornecedor, 0, 218, Short.MAX_VALUE)
                            .addComponent(txtQuantidade))
                        .addGap(0, 6, Short.MAX_VALUE)))
                .addContainerGap())
        );
        PanelCadastroLayout.setVerticalGroup(
            PanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelCadastroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LblCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblPrecoUnitario, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtPrecoUnitario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(PainelDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        BtnVoltar.setText("Voltar");
        BtnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnVoltarActionPerformed(evt);
            }
        });

        BtnSalvar.setText("Salvar");
        BtnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSalvarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PanelCadastro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BtnVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BtnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PanelCadastro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(BtnVoltar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeActionPerformed

    private void cmbFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbFornecedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbFornecedorActionPerformed

    private void BtnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSalvarActionPerformed
        try {
            extraiCampos();
        
            if(dao.verificaProduto(produto.getNome(),produto.getPrecoUnitario())){
                System.out.println("Produto "+produto.getNome()+" já cadastrado");
            }
            
            else{
                if(bd_Produto.Salvar(produto)){
                    JOptionPane.showMessageDialog(null,"Produto: "+produto.getNome()+" cadastrado"
                    + " com sucesso!!! ");
                    limpaCampos();
                }
                
                else JOptionPane.showMessageDialog(null, "Falha ao cadastrar novo Produto");
            }
        
        } catch (ErroValidacao ex) {
            ex.printStackTrace();
        } catch (NumberFormatException ex){
            ex.printStackTrace();
        }
        
    }//GEN-LAST:event_BtnSalvarActionPerformed

    private void BtnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnVoltarActionPerformed
        try {
            this.doDefaultCloseAction();
            TelaGerenciarProduto tela = new TelaGerenciarProduto();
            tela.abreFrame(tela);
        } catch (ParseException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_BtnVoltarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnSalvar;
    private javax.swing.JButton BtnVoltar;
    private javax.swing.JLabel LblCodigo;
    private javax.swing.JLabel LblPrecoUnitario;
    private javax.swing.JPanel PainelDescricao;
    private javax.swing.JPanel PanelCadastro;
    private javax.swing.JTextField TxtPrecoUnitario;
    private javax.swing.JComboBox cmbFornecedor;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblFornecedor;
    private javax.swing.JLabel lblQuantidade;
    private javax.swing.JTextArea txtDescricao;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtQuantidade;
    // End of variables declaration//GEN-END:variables

    private void extraiCampos() throws ErroValidacao {    
        if(!txtNome.getText().equals(""))
            produto.setNome(txtNome.getText());
        if(!TxtPrecoUnitario.getText().equals(""))
            produto.setPrecoUnitario(BigDecimal.valueOf(Float.parseFloat(TxtPrecoUnitario.getText())));
        if(!txtDescricao.getText().equals(""))
            produto.setDescricao(txtDescricao.getText());
        if(!txtQuantidade.getText().equals(""))
            produto.setQuantidade(Integer.parseInt(txtQuantidade.getText()));
          
        int codigo = 0;
        ArrayList<Fornecedor> listafornecedor = dao.listarFornecedores();
        for(Fornecedor novo: listafornecedor){
            if(novo.getNome().equals(cmbFornecedor.getSelectedItem()))
                codigo = novo.getId();
        }
        produto.setFornecedor_fk(codigo);
        System.out.println("Codigo selecionado: "+codigo);
    }
    
    public void carregarCombo(){
        ArrayList<Fornecedor> listafornecedor = dao.listarFornecedores();
        cmbFornecedor.addItem("Selecione");
        for(Fornecedor novo: listafornecedor){
            cmbFornecedor.addItem(novo.getNome());
        }
    }

    private void limpaCampos() {
        txtNome.setText("");
        txtDescricao.setText("");
        TxtPrecoUnitario.setText("");
        cmbFornecedor.setSelectedIndex(0);
        txtQuantidade.setText(null);
    }

    void setEntidade(Produto entidade) {
        this.produto = entidade;
        preencheCampos();
    }

    void setListagem(TelaGerenciarProduto aThis) {
        this.listagem = listagem;
    }

    private void preencheCampos() {
        txtNome.setText(produto.getNome());
        TxtPrecoUnitario.setText(String.valueOf(produto.getPrecoUnitario()));
        txtDescricao.setText(produto.getDescricao());
        txtQuantidade.setText(String.valueOf(produto.getQuantidade()));
        
        ArrayList<Fornecedor> novaLista = dao.listarFornecedores();
        for(Fornecedor novo: novaLista){
            if(novo.getId() == produto.getFornecedor_fk())
                cmbFornecedor.setSelectedItem(novo.getNome());
        }
    }
}
